fivejars/booster_drupal

config/install/core.entity_form_display.node.page.default.yml
config/install/core.entity_view_display.node.page.default.yml
config/install/field.field.node.page.body.yml
config/install/node.settings.yml
config/install/node.type.page.yml

[ ] Login as admin
[ ] Go to content page `/admin/content`
[ ] Click the button 'add content'
[ ] Ensure that the content type has the name `basic page`
[ ] Ensure that the content type has title and description fields

[FJD-11] Add basic page CT

---

Jenkinsfile

-  Create PR
- Rebase branch
- Force push
- Ensure that build success recreated

[FJD-000] Remove previous build before new one

---

Jenkinsfile
composer.json
config/install/core.entity_form_display.node.page.default.yml
starterkit.info.yml

Ensure that enabled follow modules:

[FJD-12] Add SEO module

---

composer.json
config/install/password_policy.password_policy.default.yml
starterkit.info.yml

Jira issue: [FJD-15](https://fivejars.atlassian.net/browse/FJD-15)
Ensure that enabled following modules:

[FJD-15] Security modules

---

composer.json
composer.libraries.json
config/install/core.entity_form_display.media.document.default.yml
config/install/core.entity_form_display.media.document.media_library.yml
config/install/core.entity_form_display.media.image.default.yml
config/install/core.entity_form_display.media.image.media_library.yml
config/install/core.entity_form_display.media.video.default.yml
config/install/core.entity_form_display.media.video.media_library.yml
config/install/core.entity_view_display.media.document.default.yml
config/install/core.entity_view_display.media.document.media_library.yml
config/install/core.entity_view_display.media.image.default.yml
config/install/core.entity_view_display.media.image.media_library.yml
config/install/core.entity_view_display.media.video.default.yml
config/install/core.entity_view_display.media.video.media_library.yml
config/install/field.field.media.document.field_media_document.yml
config/install/field.field.media.image.field_media_image.yml
config/install/field.field.media.video.field_media_video_file.yml
config/install/field.storage.media.field_media_document.yml
config/install/field.storage.media.field_media_image.yml
config/install/field.storage.media.field_media_video_file.yml
config/install/media.type.document.yml
config/install/media.type.image.yml
config/install/media.type.video.yml
starterkit.info.yml

Jira issue:
- Ensure that enabled follow modules:

[FJD-13] Add media modules

---

composer.json
starterkit.info.yml

[FJD-16] Webforms setup

---

config/install/editor.editor.basic_html.yml
config/install/editor.editor.full_html.yml
config/install/field.field.node.page.body.yml
config/install/filter.format.basic_html.yml
config/install/filter.format.full_html.yml
starterkit.info.yml

[FJD-17] WYSIWYG configuration

---

composer.json
config/install/config_split.config_split.dev.yml
starterkit.info.yml

Jira issue: [FJD-8](https://fivejars.atlassian.net/browse/FJD-8)
Ensure that enabled following modules: 
Ensure that added and disabled following modules:

[FJD-8] Add all dev modules

---

config/install/core.entity_form_display.node.page.default.yml
config/install/core.entity_view_display.node.page.default.yml
config/install/field.field.node.page.layout_builder__layout.yml
config/install/field.storage.node.layout_builder__layout.yml
starterkit.info.yml

Jira issue:
Ensure that enabled following modules:

[FJD-20] add Page Layout Builder

---

config/install/workflows.workflow.default.yml

Jira issue: [FJD-29](https://fivejars.atlassian.net/browse/FJD-29)

[FJD-29] Workflow modules: Content moderation statuses

---

composer.json
starterkit.info.yml

Jira issue: [FJD-26](https://fivejars.atlassian.net/browse/FJD-26)

[FJD-26] LB Styles

---

composer.json
starterkit.info.yml

Jira issue: [FJD-27](https://fivejars.atlassian.net/browse/FJD-27)
Ensure that enabled following module:

[FJD-27] Section Library

---

composer.json
starterkit.info.yml

[FJD-25] Add LB Lock

---

config/install/block_content.type.basic.yml
config/install/block_content.type.image_block.yml
config/install/core.entity_form_display.block_content.basic.default.yml
config/install/core.entity_form_display.block_content.image_block.default.yml
config/install/core.entity_view_display.block_content.basic.default.yml
config/install/core.entity_view_display.block_content.image_block.default.yml
config/install/field.field.block_content.basic.body.yml
config/install/field.field.block_content.image_block.field_image.yml
config/install/field.storage.block_content.field_image.yml
config/install/media_directories.settings.yml
config/install/taxonomy.vocabulary.media_directories.yml
starterkit.info.yml

[FJD-21] Add blocks (text and image) for LB

---

composer.json
starterkit.info.yml

Jira issue:
Ensure that enabled following module:

[FJD-22] Add block library

---

composer.json
config/install/layout_builder_browser.layout_builder_browser_block.image_block.yml
config/install/layout_builder_browser.layout_builder_browser_block.text_block.yml
config/install/layout_builder_browser.layout_builder_browser_blockcat.basic_blocks.yml
starterkit.info.yml

[FJD-24] Add LB Browser

---

composer.json
config/install/system.theme.yml
starterkit.info.yml

[FJD-31] W3CSS Theme

---

composer.json
starterkit.info.yml

Jira issue: [FJD-44](https://fivejars.atlassian.net/browse/FJD-44)
Ensure that enabled following modules:

[FJD-44] Explore and add SEO checklist module

---

config/install/core.entity_form_display.node.page.default.yml
config/install/core.entity_view_display.node.page.default.yml
config/install/field.field.node.page.field_seo_status.yml
config/install/field.storage.node.field_seo_status.yml

[FJD-37] YOAST SEO configuration for Basic page

---

config/install/core.entity_form_display.node.page.default.yml
config/install/core.entity_view_display.node.page.default.yml
config/install/field.field.node.page.field_meta_tags.yml
config/install/field.storage.node.field_meta_tags.yml

[FJD-35] Metatag configuration for Basic page

---

config/install/pathauto.pattern.basic.yml

[FJD-36] Pathauto configuration for Basic page

---

config/install/core.entity_form_display.node.page.default.yml
config/install/node.type.page.yml

[FJD-38] Scheduler configuration for Basic page

---

composer.json
config/install/core.entity_form_display.node.page.default.yml
config/install/workflows.workflow.default.yml
starterkit.info.yml

[FJD-39] Content moderation configuration for Basic page

---

composer.json

[FJD-32] Security - TFA

---

modules/starterkit_lb/css/starterkit_lb.modal.css

[FJD-61] Fix styles modal LB

---

config/install/user.role.administrator.yml
config/install/user.role.anonymous.yml
config/install/user.role.authenticated.yml
config/install/user.role.content_editor.yml
config/install/user.role.content_moderator.yml
config/install/user.role.webform_admin.yml
starterkit.info.yml

Jira issue: [FJD-55](https://fivejars.atlassian.net/browse/FJD-55)

[FJD-55] Create user roles

---

composer.json
config/install/editor.editor.full_html.yml
starterkit.info.yml

Jira issue: [FJD-75](https://fivejars.atlassian.net/browse/FJD-75)

[FJD-75] AI Assistant for WYSIWYG

---

config/install/layout_builder_styles.style.full_width.yml
modules/starterkit_lb/starterkit_lb.module

[FJD-77] Full-width layout to cover the entire width of the page

---

composer.json
config/install/core.entity_view_display.media.image.cke_media_resize_large.yml
config/install/core.entity_view_display.media.image.cke_media_resize_medium.yml
config/install/core.entity_view_display.media.image.cke_media_resize_small.yml
config/install/core.entity_view_display.media.image.cke_media_resize_xl.yml
config/install/core.entity_view_mode.media.cke_media_resize_large.yml
config/install/core.entity_view_mode.media.cke_media_resize_medium.yml
config/install/core.entity_view_mode.media.cke_media_resize_small.yml
config/install/core.entity_view_mode.media.cke_media_resize_xl.yml
config/install/editor.editor.basic_html.yml
config/install/editor.editor.full_html.yml
config/install/filter.format.basic_html.yml
config/install/filter.format.full_html.yml
starterkit.info.yml

[FJD-70] CKEditor: resize media

---

composer.json

[FJD-79] Media in block don't replace

---

composer.json
modules/starterkit_lb/css/starterkit_lb.modal.css

[FJD-61] Add patch for LB modal and fox style

---

config/install/core.entity_form_display.media.remote_video.default.yml
config/install/core.entity_form_display.media.remote_video.media_library.yml
config/install/core.entity_view_display.media.remote_video.default.yml
config/install/core.entity_view_display.media.remote_video.media_library.yml
config/install/field.field.block_content.video.field_media.yml
config/install/field.field.media.remote_video.field_media_oembed_video.yml
config/install/field.storage.media.field_media_oembed_video.yml
config/install/media.type.remote_video.yml

[FJD-66] Add remote video media type

---

config/install/filter.format.full_html.yml

[FJD-70] fix Media resize

---

composer.json

[FJD-89]: fix Positioning of the entity browser modal

---

modules/booster_lb/css/booster_lb.form.css

[FJD-83]: Import from library - when you type text it is white

---

composer.json

[FJD-81]: Webform popup is broken and not possible to close
